//! Lossless decoding and conservative updates of Sandboxie's configuration.
use crate::error::{AppError, AppResult};
use std::path::Path;

#[derive(Clone, Copy)]
enum Encoding {
    Utf8,
    Utf8Bom,
    Utf16Le,
    Utf16Be,
}

pub struct Ini {
    pub text: String,
    encoding: Encoding,
}

impl Ini {
    pub fn read(path: &Path) -> AppResult<Self> {
        match std::fs::read(path) {
            Ok(bytes) => Self::decode(&bytes),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Self::decode(&[]),
            Err(e) => Err(e.into()),
        }
    }

    fn decode(bytes: &[u8]) -> AppResult<Self> {
        let (encoding, text) =
            if bytes.starts_with(&[0xff, 0xfe]) || bytes.starts_with(&[0xfe, 0xff]) {
                if bytes.len() % 2 != 0 {
                    return Err(AppError::Config("Sandboxie.ini: truncated UTF-16".into()));
                }
                let le = bytes[0] == 0xff;
                let words: Vec<u16> = bytes[2..]
                    .chunks_exact(2)
                    .map(|b| {
                        if le {
                            u16::from_le_bytes([b[0], b[1]])
                        } else {
                            u16::from_be_bytes([b[0], b[1]])
                        }
                    })
                    .collect();
                let text = String::from_utf16(&words)
                    .map_err(|e| AppError::Config(format!("Sandboxie.ini UTF-16: {e}")))?;
                (
                    if le {
                        Encoding::Utf16Le
                    } else {
                        Encoding::Utf16Be
                    },
                    text,
                )
            } else {
                let (encoding, data) = match bytes.strip_prefix(&[0xef, 0xbb, 0xbf]) {
                    Some(data) => (Encoding::Utf8Bom, data),
                    None => (Encoding::Utf8, bytes),
                };
                let text = std::str::from_utf8(data)
                    .map_err(|e| AppError::Config(format!("Sandboxie.ini UTF-8: {e}")))?
                    .to_string();
                (encoding, text)
            };
        Ok(Self { text, encoding })
    }

    fn encode(&self) -> Vec<u8> {
        match self.encoding {
            Encoding::Utf8 => self.text.as_bytes().to_vec(),
            Encoding::Utf8Bom => [b"\xef\xbb\xbf".as_slice(), self.text.as_bytes()].concat(),
            Encoding::Utf16Le | Encoding::Utf16Be => {
                let le = matches!(self.encoding, Encoding::Utf16Le);
                let mut bytes = if le {
                    vec![0xff, 0xfe]
                } else {
                    vec![0xfe, 0xff]
                };
                for word in self.text.encode_utf16() {
                    bytes.extend(if le {
                        word.to_le_bytes()
                    } else {
                        word.to_be_bytes()
                    });
                }
                bytes
            }
        }
    }

    pub fn save(&self, path: &Path) -> AppResult<()> {
        let bytes = self.encode();
        if path.exists() {
            if std::fs::read(path)? == bytes {
                return Ok(());
            }
            std::fs::copy(path, path.with_extension("ini.steam-shadow.bak"))?;
        }
        let temp = path.with_extension("ini.steam-shadow.tmp");
        std::fs::write(&temp, bytes)?;
        std::fs::rename(&temp, path)?;
        Ok(())
    }
}

fn section(line: &str) -> Option<&str> {
    line.trim()
        .strip_prefix('[')?
        .strip_suffix(']')
        .map(str::trim)
}

/// Remove only obsolete rules generated by older launcher versions.
pub fn isolate_steam(text: &str, main_dir: &str) -> String {
    let mut managed = false;
    text.split_inclusive('\n')
        .filter(|line| {
            if let Some(name) = section(line) {
                managed = name.to_ascii_lowercase().starts_with("steamshadow_");
            }
            if !managed {
                return true;
            }
            let Some((key, value)) = line.trim().split_once('=') else {
                return true;
            };
            let key = key.trim();
            let value = value.trim();
            !((key.eq_ignore_ascii_case("OpenFilePath")
                && (value.eq_ignore_ascii_case(&format!("{main_dir}\\*"))
                    || value.eq_ignore_ascii_case(main_dir)))
                || (key.eq_ignore_ascii_case("OpenIpcPath")
                    && (value.eq_ignore_ascii_case("*\\BaseNamedObjects*\\Steam*")
                        || value.eq_ignore_ascii_case("*\\BaseNamedObjects*\\__valve*")))
                || (key.eq_ignore_ascii_case("OpenWinClass")
                    && value.eq_ignore_ascii_case("Valve_*")))
        })
        .collect()
}

pub fn managed_boxes(text: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let mut current: Option<(String, String)> = None;
    for line in text.lines() {
        if let Some(name) = section(line) {
            if let Some(entry) = current.take() {
                out.push(entry);
            }
            if let Some(login) = name.strip_prefix("SteamShadow_") {
                current = Some((name.to_string(), login.to_string()));
            }
        } else if let Some((key, value)) = line.trim().split_once('=') {
            if key.eq_ignore_ascii_case("BoxNameTitle") {
                if let (Some((_, login)), Some(value)) =
                    (&mut current, value.trim().strip_prefix("SS:"))
                {
                    *login = value.to_string();
                }
            }
        }
    }
    if let Some(entry) = current {
        out.push(entry);
    }
    out
}

pub fn has_template(text: &str, name: &str) -> bool {
    let wanted = format!("Template_{name}");
    text.lines()
        .filter_map(section)
        .any(|s| s.eq_ignore_ascii_case(&wanted))
}

/// Repair every launcher-owned box, including accounts not launched this time.
/// Leave other sandboxes and locally defined templates alone.
pub fn repair_templates(text: &str, templates: &str) -> String {
    let mut managed = false;
    text.split_inclusive('\n')
        .filter(|line| {
            if let Some(name) = section(line) {
                managed = name.to_ascii_lowercase().starts_with("steamshadow_");
            }
            if managed {
                if let Some((key, value)) = line.trim().split_once('=') {
                    let value = value.trim();
                    if key.trim().eq_ignore_ascii_case("Template")
                        && ["Steam", "OpenBluetooth", "SkipHook"]
                            .iter()
                            .any(|n| value.eq_ignore_ascii_case(n))
                    {
                        return has_template(templates, value) || has_template(text, value);
                    }
                }
            }
            true
        })
        .collect()
}

/// Add missing defaults, preserving user overrides, comments and other sections.
pub fn merge_section(text: &str, name: &str, defaults: &str) -> String {
    let lines: Vec<&str> = text.split_inclusive('\n').collect();
    let start = lines
        .iter()
        .position(|l| section(l).is_some_and(|s| s.eq_ignore_ascii_case(name)));
    let Some(start) = start else {
        return format!(
            "{}\r\n[{name}]\r\n{}",
            text.trim_end_matches(['\r', '\n']),
            defaults.replace('\n', "\r\n")
        );
    };
    let end = (start + 1..lines.len())
        .find(|&i| section(lines[i]).is_some())
        .unwrap_or(lines.len());
    let existing: Vec<(&str, &str)> = lines[start + 1..end]
        .iter()
        .filter_map(|l| l.trim().split_once('='))
        .map(|(k, v)| (k.trim(), v.trim()))
        .collect();
    let mut missing = String::new();
    for line in defaults.lines() {
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let repeated = matches!(
            key,
            "Template" | "OpenFilePath" | "OpenIpcPath" | "OpenWinClass"
        );
        if !existing.iter().any(|(k, v)| {
            k.eq_ignore_ascii_case(key) && (!repeated || v.eq_ignore_ascii_case(value))
        }) {
            missing.push_str(line);
            missing.push_str("\r\n");
        }
    }
    if missing.is_empty() {
        return text.to_string();
    }
    let mut result: String = lines[..end].concat();
    if !result.ends_with('\n') {
        result.push_str("\r\n");
    }
    result.push_str(&missing);
    result.extend(lines[end..].iter().copied());
    result
}

#[cfg(test)]
mod tests {
    #[test]
    fn isolation_removes_only_generated_shared_profile_rules() {
        let source = "[UserBox]\nOpenFilePath=C:\\Steam\\*\n[SteamShadow_old]\nBoxNameTitle=SS:foo-bar\nOpenFilePath=C:\\Steam\\*\nOpenFilePath=C:\\Steam\\steamapps\\*\nOpenIpcPath=*\\BaseNamedObjects*\\Steam*\nOpenWinClass=Valve_*\n";
        let isolated = isolate_steam(source, "C:\\Steam");
        assert_eq!(isolated.matches("OpenFilePath=C:\\Steam\\*\n").count(), 1);
        assert!(isolated.contains("OpenFilePath=C:\\Steam\\steamapps\\*"));
        assert!(!isolated.contains("OpenWinClass=Valve_*"));
        assert!(!isolated.contains("OpenIpcPath=*\\BaseNamedObjects*\\Steam*"));
        assert_eq!(
            managed_boxes(&isolated),
            vec![("SteamShadow_old".into(), "foo-bar".into())]
        );
        assert_eq!(isolate_steam(&isolated, "C:\\Steam"), isolated);
    }
    use super::*;

    #[test]
    fn repairs_all_managed_boxes_without_touching_user_sections() {
        let source = "[SteamShadow_a]\r\nTemplate=Steam\r\nTemplate=SkipHook\r\n[DefaultBox]\r\nTemplate=Steam\r\n[steamshadow_b]\r\nTemplate = steam\r\n";
        let fixed = repair_templates(source, "[Template_SkipHook]\n");
        assert_eq!(fixed, "[SteamShadow_a]\r\nTemplate=SkipHook\r\n[DefaultBox]\r\nTemplate=Steam\r\n[steamshadow_b]\r\n");
        assert_eq!(repair_templates(&fixed, "[Template_SkipHook]\n"), fixed);
        assert_eq!(
            repair_templates(source, "[Template_Steam]\n[Template_SkipHook]\n"),
            source
        );
    }

    #[test]
    fn defaults_preserve_overrides_and_are_idempotent() {
        let source = "# comment\r\n[SteamShadow_a]\r\nEnabled=n\r\nOpenFilePath=C:\\custom\r\n[Other]\r\nEnabled=y\r\n";
        let defaults = "Enabled=y\nOpenFilePath=C:\\games\nTemplate=SkipHook\n";
        let fixed = merge_section(source, "SteamShadow_a", defaults);
        assert!(fixed.contains("Enabled=n\r\nOpenFilePath=C:\\custom"));
        assert!(fixed.ends_with("[Other]\r\nEnabled=y\r\n"));
        assert_eq!(merge_section(&fixed, "SteamShadow_a", defaults), fixed);
    }

    #[test]
    fn roundtrips_supported_encodings_and_rejects_corruption() {
        for encoding in [
            Encoding::Utf8,
            Encoding::Utf8Bom,
            Encoding::Utf16Le,
            Encoding::Utf16Be,
        ] {
            let original = Ini {
                text: "[DefaultBox]\r\n# Настройки 🎮\r\n".into(),
                encoding,
            };
            let bytes = original.encode();
            let decoded = Ini::decode(&bytes).unwrap();
            assert_eq!(decoded.text, original.text);
            assert_eq!(decoded.encode(), bytes);
        }
        assert!(Ini::decode(&[0xff, 0xfe, 0]).is_err());
        assert!(Ini::decode(&[0xff]).is_err());
    }

    #[test]
    fn saves_utf16_with_backup_and_does_not_replace_backup_on_noop() {
        let dir =
            std::env::temp_dir().join(format!("steam-shadow-ini-test-{}", rand::random::<u64>()));
        std::fs::create_dir(&dir).unwrap();
        let path = dir.join("Sandboxie.ini");
        let original = Ini {
            text: "[SteamShadow_test]\r\nTemplate=Steam\r\n# Настройки\r\n".into(),
            encoding: Encoding::Utf16Le,
        }
        .encode();
        std::fs::write(&path, &original).unwrap();
        let mut ini = Ini::read(&path).unwrap();
        ini.text = repair_templates(&ini.text, "");
        ini.save(&path).unwrap();
        ini.save(&path).unwrap();
        assert_eq!(
            std::fs::read(path.with_extension("ini.steam-shadow.bak")).unwrap(),
            original
        );
        assert!(std::fs::read(&path).unwrap().starts_with(&[0xff, 0xfe]));
        assert_eq!(
            Ini::read(&path).unwrap().text,
            "[SteamShadow_test]\r\n# Настройки\r\n"
        );
        std::fs::remove_file(&path).unwrap();
        std::fs::remove_file(path.with_extension("ini.steam-shadow.bak")).unwrap();
        std::fs::remove_dir(dir).unwrap();
    }
}
